/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.coctail;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListModel;


public class Gui extends javax.swing.JFrame {

    
    AddIngredient addIngredients = new AddIngredient(Gui.this);
    IngredientsTable ingredientsTable = new IngredientsTable(Gui.this);
    CupsTable cupsTable = new CupsTable(Gui.this);
    static Blender blender;
    ArrayList<Cup> cups = new ArrayList<>();
    
    
    public Gui() {
        initComponents();
    }
    
    public ArrayList<Ingredient> getIngredients(){
        return blender.getIngredients();
    }
    
    public ArrayList<Cup> getCups(){
        return cups;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttons = new javax.swing.JPanel();
        AddAnIngredient = new javax.swing.JButton();
        blendBtn = new javax.swing.JButton();
        PrintIngredients = new javax.swing.JButton();
        PourCup = new javax.swing.JButton();
        HowManyCups = new javax.swing.JButton();
        PrintCups = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Title = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 0, 0));
        setForeground(new java.awt.Color(255, 0, 51));
        setMaximumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(152, 219, 124));
        jPanel2.setForeground(new java.awt.Color(41, 66, 115));
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 500));

        buttons.setBackground(new java.awt.Color(152, 219, 124));
        buttons.setForeground(new java.awt.Color(56, 33, 16));

        AddAnIngredient.setBackground(new java.awt.Color(255, 71, 85));
        AddAnIngredient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddAnIngredient.setText("Add An Ingredient");
        AddAnIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAnIngredientActionPerformed(evt);
            }
        });

        blendBtn.setBackground(new java.awt.Color(255, 71, 85));
        blendBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        blendBtn.setText("Blend");
        blendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blendBtnActionPerformed(evt);
            }
        });

        PrintIngredients.setBackground(new java.awt.Color(255, 71, 85));
        PrintIngredients.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PrintIngredients.setText("Print Ingredients");
        PrintIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintIngredientsActionPerformed(evt);
            }
        });

        PourCup.setBackground(new java.awt.Color(255, 71, 85));
        PourCup.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PourCup.setText("Pour A Cup");
        PourCup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PourCupActionPerformed(evt);
            }
        });

        HowManyCups.setBackground(new java.awt.Color(255, 71, 85));
        HowManyCups.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HowManyCups.setText("How Many Cups?");
        HowManyCups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowManyCupsActionPerformed(evt);
            }
        });

        PrintCups.setBackground(new java.awt.Color(255, 71, 85));
        PrintCups.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PrintCups.setText("Print Cups Info");
        PrintCups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintCupsActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(255, 71, 85));
        Exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsLayout = new javax.swing.GroupLayout(buttons);
        buttons.setLayout(buttonsLayout);
        buttonsLayout.setHorizontalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PrintCups, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HowManyCups, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(buttonsLayout.createSequentialGroup()
                        .addGroup(buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PourCup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddAnIngredient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(blendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrintIngredients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonsLayout.setVerticalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(AddAnIngredient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PrintIngredients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PourCup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(HowManyCups)
                .addGap(18, 18, 18)
                .addComponent(PrintCups)
                .addGap(18, 18, 18)
                .addComponent(Exit))
        );

        Title.setBackground(new java.awt.Color(152, 219, 124));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setText("Cocktail App");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Let's Make some delicious cocktail😋");

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addGroup(TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TitleLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(TitleLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Exit", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION )
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void PrintCupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintCupsActionPerformed
        cupsTable.printCups();
        cupsTable.setVisible(true);
        dispose();
    }//GEN-LAST:event_PrintCupsActionPerformed

    private void HowManyCupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowManyCupsActionPerformed
        try{
            String s = JOptionPane.showInputDialog("Enter the size of your cup");
            double cupSize = Double.parseDouble(s);
            int number = (int) (blender.getVolume() / cupSize);
            JOptionPane.showMessageDialog(null, number, "Look how many: ", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "please enter a number", "Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_HowManyCupsActionPerformed

    private void PourCupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PourCupActionPerformed

        try{
            String s = JOptionPane.showInputDialog("Enter the size of your cup");
            double cupSize = Double.parseDouble(s);
            Cup cup = new Cup(cupSize, 0, 0);
            Gui.blender.pour(cup);
            cups.add(cup);
        }catch(EmptyBlenderException e1){
            JOptionPane.showMessageDialog(null, e1.getMessage(), "Exception!", JOptionPane.WARNING_MESSAGE);
        }catch(NotAbleToPourException e2){
            JOptionPane.showMessageDialog(null, e2.getMessage(), "Exception!", JOptionPane.WARNING_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "please enter a number", "Exception!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_PourCupActionPerformed

    private void PrintIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintIngredientsActionPerformed
        ingredientsTable.printIngredients();
        ingredientsTable.setVisible(true);
        dispose();
    }//GEN-LAST:event_PrintIngredientsActionPerformed

    private void blendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blendBtnActionPerformed
        try{
            blender.blend();
            blender.setBlended(true);
            JOptionPane.showMessageDialog(null, "Done!", "Blend is", JOptionPane.INFORMATION_MESSAGE);
        }catch(EmptyBlenderException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Exception!",  JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_blendBtnActionPerformed

    private void AddAnIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAnIngredientActionPerformed
        
        double Capacity = -1;
        while(true){
            try{
                String s = JOptionPane.showInputDialog("Enter the Capacity of your Blender:");
                Capacity = Double.parseDouble(s);    
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "please enter a number", "Error",JOptionPane.WARNING_MESSAGE);
            }
            if(Capacity > 0){
                blender = new Blender(Capacity, 0, 0, false);
                break;
            }
        }
        
        addIngredients.printIngredients();
        addIngredients.setVisible(true);
        dispose();
    }//GEN-LAST:event_AddAnIngredientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAnIngredient;
    private javax.swing.JButton Exit;
    private javax.swing.JButton HowManyCups;
    private javax.swing.JButton PourCup;
    private javax.swing.JButton PrintCups;
    private javax.swing.JButton PrintIngredients;
    private javax.swing.JPanel Title;
    private javax.swing.JButton blendBtn;
    private javax.swing.JPanel buttons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
