/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.coctail;

import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author user
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    static AddIngredient adding = new AddIngredient();
    static Blender blender;
    ArrayList<Cup> cups = new ArrayList<>();
    public Gui() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddAnIngredient = new javax.swing.JButton();
        Blend = new javax.swing.JButton();
        PrintIngredients = new javax.swing.JButton();
        PourCup = new javax.swing.JButton();
        HowManyCups = new javax.swing.JButton();
        PrintCups = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cupsInfo = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        AddAnIngredient.setText("Add An Ingredient");
        AddAnIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAnIngredientActionPerformed(evt);
            }
        });

        Blend.setText("Blend");
        Blend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlendActionPerformed(evt);
            }
        });

        PrintIngredients.setText("Print Ingredients");
        PrintIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintIngredientsActionPerformed(evt);
            }
        });

        PourCup.setText("Pour A Cup");
        PourCup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PourCupActionPerformed(evt);
            }
        });

        HowManyCups.setText("How Many Cups?");
        HowManyCups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowManyCupsActionPerformed(evt);
            }
        });

        PrintCups.setText("Print Cups Info");
        PrintCups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintCupsActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Blend, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrintCups, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HowManyCups, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PourCup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrintIngredients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddAnIngredient, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(AddAnIngredient)
                .addGap(18, 18, 18)
                .addComponent(Blend)
                .addGap(18, 18, 18)
                .addComponent(PrintIngredients)
                .addGap(18, 18, 18)
                .addComponent(PourCup)
                .addGap(18, 18, 18)
                .addComponent(HowManyCups)
                .addGap(18, 18, 18)
                .addComponent(PrintCups)
                .addGap(18, 18, 18)
                .addComponent(Exit)
                .addGap(34, 34, 34))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("     Cocktail App");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Let's Make some delicious cocktail😋");

        cupsInfo.setColumns(20);
        cupsInfo.setRows(5);
        jScrollPane2.setViewportView(cupsInfo);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddAnIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAnIngredientActionPerformed
        adding.setVisible(true);
    }//GEN-LAST:event_AddAnIngredientActionPerformed

    private void BlendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlendActionPerformed
        JOptionPane.showMessageDialog(null, "Done!", "Blend is", JOptionPane.INFORMATION_MESSAGE);
        try{
            blender.blend();
            blender.setBlended(true);
        }catch(EmptyBlenderException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Exception!",  
                                           JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BlendActionPerformed

    private void PrintIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintIngredientsActionPerformed
        
        ArrayList<Ingredient> arr = blender.getIngredients();
        String p = "";
        for(Ingredient i : arr){
            p += i.getInfo();
            p += "\n";
        }
        jTextArea1.setText(p);
        
    }//GEN-LAST:event_PrintIngredientsActionPerformed

    private void PourCupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PourCupActionPerformed
        String s = JOptionPane.showInputDialog("Enter the size of your cup");
        double cupSize = Double.parseDouble(s);
        Cup cup = new Cup(cupSize, 0, 0);
        try{
            Gui.blender.pour(cup);
            cups.add(cup);
        }catch(EmptyBlenderException e1){
            JOptionPane.showMessageDialog(null, e1.getMessage(), "Exception!", JOptionPane.WARNING_MESSAGE);
        }catch(NotAbleToPourException e2){
            JOptionPane.showMessageDialog(null, e2.getMessage(), "Exception!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_PourCupActionPerformed

    private void HowManyCupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowManyCupsActionPerformed
       String s = JOptionPane.showInputDialog("Enter the size of your cup");
       double cupSize = Double.parseDouble(s);
        int number = (int) (blender.getVolume() / cupSize);
        JOptionPane.showMessageDialog(null, number, "Look how many: ",  
                                           JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_HowManyCupsActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Are You Sure?", "Exit", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION )
            System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void PrintCupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintCupsActionPerformed
        String txt = "";
        for(Cup c : cups){
            txt += c.getInfo();
            txt += '\n';
        }
        cupsInfo.setText(txt);
    }//GEN-LAST:event_PrintCupsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
                String s = JOptionPane.showInputDialog("Enter the Capacity of your Blender:");
                double Capacity = Double.parseDouble(s);
                blender = new Blender(Capacity, 0, 0, false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAnIngredient;
    private javax.swing.JButton Blend;
    private javax.swing.JButton Exit;
    private javax.swing.JButton HowManyCups;
    private javax.swing.JButton PourCup;
    private javax.swing.JButton PrintCups;
    private javax.swing.JButton PrintIngredients;
    private javax.swing.JTextArea cupsInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
